"""create jobs and users tables

Revision ID: 6f2c18a71b11
Revises: 
Create Date: 2026-07-15 14:47:45.665339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2c18a71b11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('clerk_user_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_index(op.f('ix_users_clerk_user_id'),
                    'users', ['clerk_user_id'], unique=True)
    op.create_table('jobs',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('anonymous_id', sa.UUID(), nullable=True),
                    sa.Column('operation', sa.Enum('CONVERT', 'COMPRESS',
                                                   name='operation'), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING',
                                                'COMPLETED', 'FAILED', name='job_status'), nullable=False),
                    sa.Column('input_key', sa.String(), nullable=False),
                    sa.Column('output_key', sa.String(), nullable=True),
                    sa.Column('retry_count', sa.Integer(), nullable=False),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('started_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('finished_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.CheckConstraint('\n            (user_id IS NOT NULL AND anonymous_id IS NULL)\n            OR\n            (user_id IS NULL AND anonymous_id IS NOT NULL)\n            ', name=op.f(
                        'ck_jobs_ck_jobs_exactly_one_identity')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
                    )
    op.create_index(op.f('ix_jobs_anonymous_id'), 'jobs',
                    ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_anonymous_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
