services:
  postgres:
    image: postgres:18.4
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-tinkertaps}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

    ports:
      - "8000:8000"

    depends_on:
      - postgres


volumes:
  postgres_data:
